POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Musaab Abdullah",
    "number": "39-44-1441144"
}
###

GET http://localhost:3001/api/persons/5 HTTP/1.1

###

GET http://localhost:3001/info HTTP/1.1

###

DELETE  http://localhost:3001/api/persons/2 HTTP/1.1

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "do",
    "number": "456789-200000001"
}